import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chaitanya Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/portfolio-favicon.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Font Awesome */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
        <a target="_blank" href="https://icons8.com/icon/33294/code-fork">Code Fork</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a>
        {/* Bootstrap JavaScript */}
      </Head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
